apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-client
  template:
    metadata:
      labels:
        app: spiffe-client
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: client
          image: ghcr.io/spiffe/spire-agent:1.5.1
          command: ["/opt/spire/bin/spire-agent"]
          args:
            - "api"
            - "watch"
            - "-socketPath"
            - "/run/spire/sockets/agent.sock"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
